rzd_project/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, re_path
from rzd_app.views import *
from rzd_app import views

def redirect_page(request, pk=''):
    return redirect('main_page')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', start_page, name='start_page'),
    path('login/', LoginUserView.as_view(), name='login_page'),
    path('register/', RegisterUserView.as_view(), name='register_page'),
    path('main_page/', main_page, name='main_page'),
    path('register/create_user', create_user, name='create_user'),
    path('main_page/routes/<int:pk>', route_page, name='route_page'),
    path('main_page/routes/', redirect_page),
    path('main_page/<int:pk>', redirect_page),
    path('main_page/routes/chosen/<int:pk>', van_page, name='van_page'),
    path('main_page/routes/chosen/<int:tr>/<int:vn>/<int:st>/buy', buy_ticket, name='buy_ticket'),
    path('main_page/routes/chosen/<int:tr>/<int:vn>/<int:st>/reject', reject_ticket, name='reject_ticket'),
    path('main_page/my_trips', my_trips, name='my_trips'),
    path('main_page/my_trips/<int:id>/reject', reject_ticket)


]

rzd_app/models.py
from django.db import models
from django.contrib.auth.models import User
class Passenger(models.Model):
    django_user = models.ForeignKey(User, on_delete=models.CASCADE)
    last_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    patronymic = models.CharField(max_length=30, null=True, blank=True) #отчество
    age = models.IntegerField()
    about = models.CharField(max_length=250)
    contact = models.CharField(max_length=40)
    trip_with_child = models.IntegerField(choices=[
        (0, "Еду один"),
        (1, "Один ребенок"),
        (2, "Двое детей"),
        (3, "Трое детей"),
        (4, "Четверо детей"),
        (5, "Пятеро детей")

    ], default=0)
    trip_with_animals = models.BooleanField(default=False)

    #Фичи
    regular_choice = models.IntegerField(choices=[
        #(0, 'Покупаю билет впервые'),
        (1, 'Плацкарт'),
        (2, 'Купе'),
        (3, 'СВ'),
        (4, 'Люкс')
    ])

    smoking_attitude = models.IntegerField(choices=[(1, 'Крайне негативно'),
                                                    (2, 'Негативно'),
                                                    (3, 'Нейтрально'),
                                                    (4, 'Положительно'),
                                                    (5, 'Крайне положительно')])

    having_children = models.IntegerField(choices=[
        (1, 'Да'),
        (0, 'Нет')
    ])
    sociability = models.IntegerField(choices=[(1, 'Предпочитаю не общаться в поездке'),
                                               (2, 'Редко общаюсь'),
                                               (3, 'По-настроению'),
                                               (4, 'Часто общаюсь'),
                                               (5, 'Люблю заводить новые знакомства в поездах')])

    pets_attitude = models.IntegerField(choices=[
        (1, 'Положительно'),
        (0, 'Отрицательно')
    ])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}, {self.patronymic}, {self.age}, {self.about}, {self.contact},' \
               f'{self.trip_with_child}, {self.trip_with_animals},'\
               f'{self.regular_choice}, {self.smoking_attitude}, {self.having_children}, {self.sociability},' \
               f'{self.pets_attitude}, {self.django_user}'

class VanCharacter(models.Model):
    type = models.IntegerField(choices=[
        (1, 'Плацкарт'),
        (2, 'Купе'),
        (3, 'СВ'),
        (4, 'Люкс')
    ])

    class_van = models.IntegerField(choices=[
        (1, '3Б'),
        (2, '3Э'),
        (3, '2Т'),
        (4, '2Э'),
        (5, '1Э'),
        (6, '1Т'),
        (7, '1М')
    ])

    seat_quantity = models.IntegerField()

    food = models.BooleanField()
    info_entertaiment = models.BooleanField()
    linen = models.BooleanField()
    biotoilet = models.BooleanField()
    conditioner = models.BooleanField()
    cosmetic = models.BooleanField()
    press = models.BooleanField()
    pet = models.BooleanField()
    bath = models.BooleanField()
    business_lounge = models.BooleanField()
    taxi = models.BooleanField()

    def __str__(self):
        return f'{self.type}, {self.class_van}, {self.seat_quantity}, {self.food}, {self.info_entertaiment}, {self.linen},' \
               f'{self.biotoilet}, {self.conditioner}, {self.cosmetic}, {self.press},' \
               f'{self.pet}, {self.bath}, {self.business_lounge}, {self.taxi} '

class Train(models.Model):
    name = models.CharField(max_length=30)
    place1 = models.CharField(max_length=30)
    place2 = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name}, {self.place1}, {self.place2}'


class Van(models.Model):
    train = models.ForeignKey(Train, on_delete=models.CASCADE)
    character = models.ForeignKey(VanCharacter, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.train}, {self.character}'


class Seat(models.Model):
    van = models.ForeignKey(Van, on_delete=models.CASCADE)
    price = models.IntegerField(null=True)
    seat_number = models.IntegerField(null=True)

    def __str__(self):
        return f'{self.van}, {self.price}, {self.seat_number}'


class Trip(models.Model):
    passenger = models.ForeignKey(Passenger, on_delete=models.CASCADE)
    seats = models.ForeignKey(Seat, on_delete=models.CASCADE)
    finished = models.BooleanField(default=False)
    with_children = models.IntegerField(default=0)
    with_animals = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.passenger}, {self.seats}, {self.finished}, {self.with_children}, {self.with_animals}'

templates/create_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Создание нового пользователя</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="{% static 'bootstrap/css/styles.css' %}" rel="stylesheet">
    <!-- Импорт стилей из вашего шаблона -->
    <link rel="stylesheet" href="https://bootstraptema.ru/snippets/form/2022/form-page/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="https://bootstraptema.ru/snippets/form/2022/form-page/animate.min.css">
    <link rel="stylesheet" href="https://bootstraptema.ru/snippets/form/2022/form-page/fontawesome-all.css">
    <link rel="stylesheet" href="https://bootstraptema.ru/snippets/form/2022/form-page/style.css">
    <link rel="stylesheet" type="text/css" href="https://bootstraptema.ru/snippets/form/2022/form-page/switch.css">
    <!-- Color Alternatives -->
    <link href="https://bootstraptema.ru/snippets/form/2022/form-page/color-4.css" rel="alternate stylesheet" type="text/css" title="color-4">
</head>

<style>
    .bank-account-label {
        font-weight: bold;
        font-size: 20px;
    }

    .bank-account-input {
        width: 100%;
        font-size: 16px;
    }

    /* Выравнивание по верхнему краю */
    .form-area {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        height: 100vh;
        margin-top: -70px; /* Увеличьте отступ сверху, чтобы поднять все элементы */
    }

    /* Увеличиваем отступы между элементами */
    .form-group {
        margin-bottom: 20px;
    }
</style>

<body>
    <div class="wrapper">
        <div class="steps-area steps-area-fixed">
            <div class="image-holder">
                <img src="{% static 'bootstrap/img/forma.jpg' %}" alt="">
            </div>
        </div>
        <form class="multisteps-form__form" action="" id="wizard" method="POST">
            {% csrf_token %}
            <div class="form-area position-relative">
                <div class="multisteps-form__panel js-active" data-animation="slideHorz">
                    <div class="wizard-forms">
                        <div class="inner pb-100 clearfix">
                            <div class="form-content pera-content">
                                <div class="step-inner-content">
                                    <h2>Заполните личные данные</h2>
                                    <p>Ваши данные необходимы для создания персональных рекомендаций и покупки билетов на рейсы РЖД</p>
                                    <!-- Форма с полями для ввода информации о пользователе -->
                                    <form method="post">
                                        {% csrf_token %}
                                        <div class="form-group mb-3">
                                            {{ form.last_name }}
                                        </div>
                                        <div class="form-group mb-3">
                                            {{ form.first_name }}
                                        </div>
                                        <div class="form-group mb-3">
                                            {{ form.patronymic }}
                                        </div>
                                        <div class="form-group mb-3">
                                            {{ form.age }}
                                        </div>
                                        <div class="form-group mb-3">
                                            <h2>Расскажите о себе</h2>
                                            <p>Контакты необходимы для знакомства и общения с предстоящими попутчиками</p>
                                        </div>
                                        <div class="form-group mb-3">
                                            {{ form.contact }}
                                        </div>
                                        <div class="form-group mb-3">
                                            {{ form.about }}
                                        </div>
                                        <h2>Заполните анкету</h2>
                                        <p>Анкета поможет нам правильно сформировать рекомендации и сделать вашу поездку еще комфортнее</p>
                                         <div class="form-group mb-3">
                                             <label style="font-size: 20px;">Чаще всего предпочитаете</label>
                                            {{ form.regular_choice }}
                                        </div>
                                        <div class="form-group mb-3">
                                            <label style="font-size: 20px;">Ваше отношение к курящим попутчикам</label>
                                            {{ form.smoking_attitude }}
                                        </div>
                                        <div class="form-group mb-3">
                                            <label style="font-size: 20px;">Планируете ли вы путешествовать с ребенком</label>
                                            {{ form.having_children }}
                                        </div>
                                        <div class="form-group mb-3">
                                            <label style="font-size: 20px;">Оцените, насколько Вы общительны в поездке</label>
                                            {{ form.sociability }}
                                        </div>
                                        <div class="form-group mb-3">
                                            <label style="font-size: 20px;">Ваше отношение к попутчикам с домашними животными</label>
                                            {{ form.pets_attitude }}
                                        </div>

                                        <span>{{ error }}</span>
                                    </form>
                                    <hr class="my-4" />
                                     <p>Нажимая кнопку "Завершить регистрацию", Вы даете согласие на обработку и использование Ваших персональных данных.</p>
<button class="btn btn-danger btn-lg float-right" type="submit">Завершить регистрацию</button>
<a href="{% static 'bootstrap/Согласие_на_обработку_персональных_данных.docx' %}" target="_blank" style="text-decoration: underline; font-weight: bold;">Ознакомиться с согласием</a>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</body>

</html>

templates/login_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap-icons.css">
    <link href="{% static 'bootstrap/css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/headers.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/features.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/badges.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/product.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/pricing.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Google fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com/">
    <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&display=swap" rel="stylesheet">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'bootstrap/css/styles.css' %}" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/inputmask/5.0.6/jquery.inputmask.min.js"></script>
</head>
<body class="img js-fullheight"
      style="background-image: url('{% static 'bootstrap/img/p-fon.jpg' %}'); background-size: cover;">

<div class="container position-absolute top-0 start-0 mt-3 ms-3">
    <a id="backButton" href="{% url 'start_page' %}" class="btn btn-danger">
        <i class="bi bi-arrow-left"></i> Назад
    </a>
</div>


<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <h2 class="heading-section"
                    style="color: white; font-size: 3.5em; font-family: 'Kanit', sans-serif; font-weight: bold;">
                    Авторизация</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
                <div class="login-wrap p-0">
                    <h3 class="mb-4 text-center"
                        style="color: white; font-size: 1.7em; font-family: 'Kanit', sans-serif; font-weight: regular;">
                        У вас уже есть аккаунт?</h3>
                    <form id="add_form" method="post">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            <input type="text" class="form-control form-control-lg w-100"
                                   name="{{ form.username.name }}" placeholder="{{ form.username.label }}" required>
                        </div>
                        <div class="form-group mb-3">
                            <input id="password-field" type="password" class="form-control form-control-lg w-100"
                                   name="{{ form.password.name }}" placeholder="{{ form.password.label }}" required>
                        </div>

                        <button type="submit" class="btn btn-danger btn-lg w-100 mb-2">Войти</button>


                        <div class="form-group">
                            <div class="form-group">
                                <label style="color: white;">
                                    <input type="checkbox" checked> Запомнить меня
                                </label>
                            </div>

                            {% if form.errors %}
                            <p class="error-message" style="color: red; font-weight: bold;">Неверный логин или
                                пароль</p>
                            {% endif %}

                        </div>
                    </form>
                    <!-- Уведомление об ошибке -->
                    <div id="error-notification" class="alert alert-danger" style="display: none;"></div>
                </div>
            </div>
        </div>
    </div>
</section>


<!-- Include JavaScript dependencies here -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap/js/scripts.js' %}"></script>
<script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/popper.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap/js/main.js' %}"></script>
<script>


</script>
</section>
</body>
</html>

templates/main_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Личный кабинет</title>
        <link href="{% static 'bootstrap/css/new.css' %}" rel="stylesheet">
    <style>


        body {
            font-family: Arial, sans-serif;
            background-color: rgb(250, 250, 250);
            margin: 0;
            padding: 0;
        }

 header {
    background-color: rgb(230, 0, 0);
    color: #fff;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 20px;
}

.align-right {
    margin-left: auto;
}


        h1 {
            font-size: 24px;
            margin: 0;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border: 1px solid rgb(135, 145, 155);
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }

        button {
            background-color: rgb(230, 0, 0);
            color: #fff;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
        }

        .btn-danger {
            background-color: rgb(230, 0, 0);
            color: #fff;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
        }

        .btn-lg {
            font-size: 20px;
        }

        .float-right {
            float: right;
        }

        .btn-container {
            text-align: right;
            margin-top: 10px;
        }

        form {
            margin-top: 20px;
        }

            .form-group {
        margin-bottom: 15px;
    }

        h2 {
            font-size: 20px;
            margin-top: 20px;
        }

        .route {
            border: 1px solid rgb(135, 145, 155);
            padding: 10px;
            margin: 10px 0;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
    </style>
</head>
<body>
<header>
    <a href="../" class="btn btn-primary btn-lg align-right">
        <button type="submit">Выйти из аккаунта</button>
    </a>

        <div class="btn-container">
        <a href="./my_trips" class="btn btn-primary btn-lg">
            <button type="submit">Мои поездки</button>
        </a>
    </div>
</header>

<div class="container">
    <h1>Добро пожаловать, {{user.first_name}} {{user.patronymic}}!</h1>

<form id="add_form" method="post">
    {% csrf_token %}

    <div class="form-group mb-3">
        <label style="font-size: 16px;">Дети в поездке: </label>
        {{ form.trip_with_child }}
    </div>

    <div class="form-group mb-3">
        <label style="font-size: 16px;">Еду с животным: </label>
        {{ form.trip_with_animals }}
    </div>

    <button form="add_form" type="submit" class="btn btn-primary">Сохранить</button>
</form>


    <h2>Выберите маршрут следования</h2>
    {% for p in train %}
    <div class="route">
        <span>{{p.place1}} - {{p.place2}} / {{p.place2}} - {{p.place1}}</span>
        <a href="./routes/{{p.id}}"><button>{{p.name}}</button></a>
    </div>
    {% endfor %}
</div>
</body>
</html>

templates/my_trips.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Мои поездки</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: rgb(250, 250, 250);
            margin: 0;
            padding: 0;
        }
        .container {
            margin-top: 20px; /* Смещаем контейнер вверх */
            margin-left: 20px; /* Добавляем отступ слева */
            display: flex;
            flex-direction: column;
            align-items: flex-start; /* Выравнивание по левому краю */
            justify-content: center;
        }
        .ticket-container {
            width: 30%; /* Уменьшаем ширину бокса с информацией о поездке */
            margin-left: 20px; /* Добавляем отступ слева */
        }
        .ticket {
            background-color: white;
            border: 1px solid rgb(230, 0, 0);
            padding: 15px;
            margin: 10px;
            border-radius: 5px;
        }
        h2 {
            color: rgb(230, 0, 0);
            margin-left: 20px; /* Добавляем отступ слева для заголовка */
        }
        p {
            color: rgb(135, 145, 155);
            margin-left: 20px; /* Добавляем отступ слева для текста */
        }
        button {
            background-color: rgb(230, 0, 0);
            color: white;
            border: none;
            padding: 10px 15px;
            margin: 10px;
            cursor: pointer;
            border-radius: 5px;
        }
        button:hover {
            background-color: rgb(0, 0, 0);
        }
    </style>
</head>
<body>
    <div class="container">
        <a href="./"><button>Назад</button></a>
        <h2>Предстоящие поездки: </h2>
        {% if active != None %}
            {% for p in active %}
                <div class="ticket-container">
                    <div class="ticket">
                        <p>Маршрут: {{p.seats.van.train.name}}</p>
                        <p>Класс обслуживания: {{p.seats.van.character.get_class_van_display}}</p>
                        <p>Номер места: {{p.seats.seat_number}}</p>
                        <a href="./my_trips/{{p.id}}/reject"><button>Отказаться от билета</button></a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>На текущий момент Вам не предстоит поездок.</p>
        {% endif %}
        <h2>Завершенные поездки: </h2>
        {% if finished == None %}
            <p>У Вас пока нет завершенных поездок</p>
        {% else %}
            {% for p in finished %}
                <div class="ticket-container">
                    <div class="ticket">
                        <p>Маршрут: {{p.seats.van.train.name}}</p>
                        <p>Класс обслуживания: {{p.seats.van.character.get_class_van_display}}</p>
                        <p>Номер места: {{p.seats.seat_number}}</p>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</body>
</html>

templates/register_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap-icons.css">
    <link href="{% static 'bootstrap/css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/headers.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/features.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/badges.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/product.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/pricing.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Google fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com/">
    <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&display=swap" rel="stylesheet">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'bootstrap/css/styles.css' %}" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/inputmask/5.0.6/jquery.inputmask.min.js"></script>
</head>
<body class="img js-fullheight"
      style="background-image: url('{% static 'bootstrap/img/p-fon.jpg' %}'); background-size: cover; height: 100%; overflow: hidden;">

<div class="container position-absolute top-0 start-0 mt-3 ms-3">
    <a id="backButton" href="{% url 'start_page' %}" class="btn btn-danger">
        <i class="bi bi-arrow-left"></i> Назад
    </a>
</div>

<div class="container" style="margin-top: 100px; text-align: center; height: 100vh; overflow: hidden;">
    <!-- Добавляем стили здесь -->
    <div class="row justify-content-center">
        <div class="col-md-6 text-center mb-5">
            <h2 class="heading-section"
                style="color: white; font-size: 3.5em; font-family: 'Kanit', sans-serif; font-weight: bold;">
                Регистрация</h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4">
            <div class="login-wrap p-0" style="margin-top: -18px;">
                <h3 class="mb-4 text-center"
                    style="color: white; font-size: 1.7em; font-family: 'Kanit', sans-serif; font-weight: regular;">
                    Создать аккаунт?</h3>
                <form id="add_form" method="post">
                    {% csrf_token %}
                    <div class="form-group mb-3">
                        <input type="text" class="form-control form-control-lg w-100"
                               name="username" placeholder="{{ form.username.label }}" required>
                    </div>
                    <div class="form-group mb-3">
                        <input id="password-field" type="password" class="form-control form-control-lg w-100"
                               name="password" placeholder="{{ form.password.label }}" required>
                    </div>
                    <div class="form-group mb-3">
                        <button form="add_form" type="submit" class="btn btn-danger btn-lg w-100">
                            Добавить
                        </button>
                    </div>
                    <div class="form-group">
                        <div class="form-group" style="color: white; text-align: left;">
                            <label>
                                <input type="checkbox" checked> Запомнить меня
                            </label>
                        </div>
                    </div>
                </form>
                <!-- Уведомление об ошибке -->
                <div id="error-notification" style="color: red; font-weight: bold; text-align: left; display: none;">
                    Не более 150 символов. Можно использовать только буквы, цифры и символы @/./+/-/_
                </div>

            </div>
        </div>
    </div>
</div>

<!-- Include JavaScript dependencies here -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap/js/scripts.js' %}"></script>
<script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/popper.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap/js/main.js' %}"></script>

<script>
document.getElementById("add_form").addEventListener("submit", function (event) {
    var username = document.querySelector("#add_form input[name='username']").value;
    var password = document.querySelector("#password-field").value;

    // Проверка на допустимые символы и максимальную длину
    var validCharacters = /^[a-zA-Z0-9@/./+/-/_]+$/;
    if (!validCharacters.test(password) || password.length > 150) {
        // Отображение уведомления
        var notification = document.getElementById("error-notification");
        notification.style.border = "none"; // Убираем рамку
        notification.style.display = "block";

        // Остановка отправки формы
        event.preventDefault();
    }
});

// Получаем URL предыдущей страницы
var previousPageUrl = document.referrer;

// Находим кнопку "Назад" по её ID
var backButton = document.getElementById("backButton");

// Устанавливаем атрибут href для кнопки "Назад" равным URL предыдущей страницы
backButton.href = previousPageUrl;

</script>

</body>
</html>